export enum Configuration {
  PORT_DB = 'PORT_DB',
  PORT_SERVER = 'PORT_SERVER',
  HOST = 'HOST',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  SYNCHRONIZE = 'SYNCHRONIZE',
  TYPE = 'TYPE',
}
